# Generated by Django 2.1.8 on 2019-06-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=64, null=True)),
                ('intro', models.CharField(max_length=256, null=True)),
                ('mediaUuid', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('tags', models.ManyToManyField(to='manager.Tag')),
            ],
            options={
                'db_table': 'tb_album',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('activitUuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitSignUuid', to='manager.Activity', to_field='uuid')),
                ('userUuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSignUuid', to='manager.User', to_field='uuid')),
            ],
            options={
                'db_table': 'tb_sign',
            },
        ),
        migrations.RenameField(
            model_name='templatestory',
            old_name='mediaUuid',
            new_name='faceMediaUuid',
        ),
        migrations.RemoveField(
            model_name='viewpager',
            name='worksUuid',
        ),
        migrations.AddField(
            model_name='rank',
            name='workUuid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workRankUuid', to='manager.Works', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='templatestory',
            name='listMediaUuid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='viewpager',
            name='targetUuid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='checkInfo',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='checkStatus',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='templateUuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateStoryUuid', to='manager.TemplateStory', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='works',
            name='albumUuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumWorkUuid', to='manager.Album', to_field='uuid'),
        ),
    ]
