# Generated by Django 2.1.8 on 2019-06-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='bgmvolume',
            new_name='bgmVolume',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='uservolume',
            new_name='userVolume',
        ),
        migrations.AddField(
            model_name='tag',
            name='iconMediaUuid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sortNum',
            field=models.IntegerField(null=True, verbose_name='排序编号'),
        ),
        migrations.AddField(
            model_name='templatestory',
            name='isRecommd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatestory',
            name='status',
            field=models.CharField(default='normal', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Tag', to_field='uuid'),
        ),
    ]
