# Generated by Django 2.1.8 on 2019-06-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatestory',
            name='isRecommd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatestory',
            name='status',
            field=models.CharField(default='normal', max_length=32, null=True),
        ),
    ]
