# Generated by Django 2.1.8 on 2019-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190621_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='bgmvolume',
            new_name='bgmVolume',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='uservolume',
            new_name='userVolume',
        ),
        migrations.AddField(
            model_name='tag',
            name='iconMediaUuid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
