# Generated by Django 2.1.8 on 2019-06-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190621_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='isUpload',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='works',
            name='moduleUuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moduleWorksUuid', to='manager.Module', to_field='uuid'),
        ),
    ]
