# Generated by Django 2.1.8 on 2019-06-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190619_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='workUuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workRankUuid', to='manager.Works', to_field='uuid'),
        ),
    ]
