# Generated by Django 2.1.8 on 2019-06-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190619_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='searchHistoryUuid',
        ),
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
