# Generated by Django 2.1.8 on 2019-06-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190620_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forbiddenType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastvisit',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
