# Generated by Django 2.1.8 on 2019-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190620_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
