# Generated by Django 2.1.8 on 2019-06-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_version_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mediaUuid',
        ),
        migrations.AddField(
            model_name='user',
            name='userLogo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
