# Generated by Django 2.1.8 on 2019-06-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190620_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='logDate',
        ),
    ]
